export const GENRES = ["All", "Documentary", "Comedy", "Horror", "Crime"];

export const MOVIES_LIST = [
  {
    id: "001",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "002",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "003",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "004",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "005",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "006",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "007",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "008",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "009",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
  {
    id: "010",
    imageSource: "",
    description: "The best Tarantino's movie",
    title: "Pulp fiction",
    date: "1994-04-27",
    genres: ["Comedy", "Crime"],
    url: "https://netflix.com/movies/pulp-fiction",
    rating: 87,
    runtime: 6120000,
  },
];
